
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sina
 */
public class UpdateUI extends javax.swing.JFrame {
    InsurancePolicy policy;
    UserUI userUI;

    /**
     * Creates new form UpdateUI
     */
    public UpdateUI(InsurancePolicy policy, UserUI userUI) {
        this.policy = policy;
        this.userUI = userUI;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        policyTypeButtonGroup = new javax.swing.ButtonGroup();
        comprehensiveRadioButton = new javax.swing.JRadioButton();
        thirdPartyRadioButton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        policyIdField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        holderNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        carModelField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        manufacturingYearField = new javax.swing.JTextField();
        carTypeComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        numberOfClaimsField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        yearField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        monthField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        dayField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        driverAgeLabel = new javax.swing.JLabel();
        driverAgeField = new javax.swing.JTextField();
        levelLabel = new javax.swing.JLabel();
        levelField = new javax.swing.JTextField();
        commentLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();
        addPollicyButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        cancelPollicyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        policyTypeButtonGroup.add(comprehensiveRadioButton);
        comprehensiveRadioButton.setText("Comprehensive");
        comprehensiveRadioButton.setEnabled(false);
        comprehensiveRadioButton.setSelected(policy instanceof ComprehensivePolicy);
        comprehensiveRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                policyTypeRadioItemStateChange(evt);
            }
        });

        policyTypeButtonGroup.add(thirdPartyRadioButton);
        thirdPartyRadioButton.setText("Third Party");
        thirdPartyRadioButton.setToolTipText("");
        thirdPartyRadioButton.setEnabled(false);
        thirdPartyRadioButton.setSelected(policy instanceof ThirdPartyPolicy);
        thirdPartyRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                policyTypeRadioItemStateChange(evt);
            }
        });

        jLabel9.setText("Policy ID");

        policyIdField.setText(policy.getId()+"");
        policyIdField.setEnabled(false);

        jLabel10.setText("Holder Name");

        holderNameField.setText(policy.getPolicyHolderName());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel11.setText("Car");

        jLabel12.setText("Type");

        jLabel13.setText("Model");

        carModelField.setText(policy.getCar().getModel());

        jLabel14.setText("Price");

        priceField.setText(policy.getCar().getPrice()+"");
        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Manufactury Year");

        manufacturingYearField.setText(policy.getCar().getManufacturingYear()+"");

        carTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(CarType.values()));
        carTypeComboBox.setSelectedItem(policy.getCar().getType());

        jLabel16.setText("Number of Claims");

        numberOfClaimsField.setText(policy.getNumberOfClaims()+"");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel17.setText("Expiry Date");

        yearField.setText(policy.getExpiryDate().getYear()+"");

        jLabel18.setText("/");

        monthField.setText(policy.getExpiryDate().getMonth()+"");
        monthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthFieldActionPerformed(evt);
            }
        });

        jLabel19.setText("/");

        dayField.setText(policy.getExpiryDate().getDay()+"");

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        driverAgeLabel.setText("Driver Age");

        driverAgeField.setText(policy instanceof ComprehensivePolicy ? ((ComprehensivePolicy) policy).getDriverAge()+"" : "");

        levelLabel.setText("Level");

        levelField.setText(policy instanceof ComprehensivePolicy ? ((ComprehensivePolicy) policy).getLevel()+"" : "");

        commentLabel.setText("Comments");

        commentsTextArea.setColumns(16);
        commentsTextArea.setRows(4);
        commentsTextArea.setText(policy instanceof ThirdPartyPolicy ? ((ThirdPartyPolicy) policy).getComments() : "");
        jScrollPane1.setViewportView(commentsTextArea);
        policyTypeRadioItemStateChange(null);

        addPollicyButton.setText("Update");
        addPollicyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPollicyButtonActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel24.setText("General Information");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel25.setText("Additional Information");

        cancelPollicyButton.setText("Cancel");
        cancelPollicyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPollicyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comprehensiveRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thirdPartyRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(commentLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yearField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19)
                                        .addGap(12, 12, 12)
                                        .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(priceField)
                                            .addComponent(manufacturingYearField)
                                            .addComponent(carModelField)
                                            .addComponent(carTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(holderNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(policyIdField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numberOfClaimsField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(driverAgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(driverAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(levelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton)
                    .addComponent(addPollicyButton)
                    .addComponent(cancelPollicyButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thirdPartyRadioButton)
                            .addComponent(comprehensiveRadioButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clearButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPollicyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelPollicyButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(policyIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(holderNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(numberOfClaimsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(carModelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(carTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(manufacturingYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(driverAgeLabel)
                            .addComponent(driverAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(levelLabel)
                            .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void policyTypeRadioItemStateChange(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_policyTypeRadioItemStateChange
        driverAgeLabel.setVisible(comprehensiveRadioButton.isSelected());
        driverAgeField.setVisible(comprehensiveRadioButton.isSelected());
        levelLabel.setVisible(comprehensiveRadioButton.isSelected());
        levelField.setVisible(comprehensiveRadioButton.isSelected());
        commentLabel.setVisible(thirdPartyRadioButton.isSelected());
        jScrollPane1.setVisible(thirdPartyRadioButton.isSelected());
    }//GEN-LAST:event_policyTypeRadioItemStateChange

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void monthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        policyIdField.setText("");
        holderNameField.setText("");
        numberOfClaimsField.setText("");
        carModelField.setText("");
        carTypeComboBox.setSelectedIndex(0);
        priceField.setText("");
        manufacturingYearField.setText("");
        yearField.setText("");
        monthField.setText("");
        dayField.setText("");
        driverAgeField.setText("");
        levelField.setText("");
        commentsTextArea.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed
                                          
    private Integer safeGetInputInteger(String value) {
        try {
            int number = Integer.parseInt(value);
            if (number < 0) throw new Exception();
            return number;
        } catch (Exception e) {
            return null;
        }
    }                                           

    private Double safeGetInputDouble(String value) {
        try {
            Double number = Double.parseDouble(value);
            if (number < 0) throw new Exception();
            return number;
        } catch (Exception e) {
            return null;
        }
    }
    
    private void addPollicyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPollicyButtonActionPerformed
        String errorMessage = "";

        Integer policyId = safeGetInputInteger(policyIdField.getText());
        String holderName = holderNameField.getText();
        Integer numberOfClaims = safeGetInputInteger(numberOfClaimsField.getText());
        String carModel = carModelField.getText();
        CarType carType = (CarType) carTypeComboBox.getSelectedItem();
        Double price = safeGetInputDouble(priceField.getText());
        Integer manufacturingYear = safeGetInputInteger(manufacturingYearField.getText());
        Integer year = safeGetInputInteger(yearField.getText());
        Integer month = safeGetInputInteger(monthField.getText());
        Integer day = safeGetInputInteger(dayField.getText());
        Integer driverAge = safeGetInputInteger(driverAgeField.getText());
        Integer level = safeGetInputInteger(levelField.getText());
        String comments = commentsTextArea.getText();
        if (policyId == null) errorMessage = "Policy ID should be a number and greater than Zero!";
        else if (holderName.isEmpty()) errorMessage = "Holder Name is required!";
        else if (numberOfClaims == null) errorMessage = "Number of Claims should be a number and greater than Zero!";
        else if (carModel.isEmpty()) errorMessage = "Model is required!";
        else if (price == null) errorMessage = "Price should be a number and greater than Zero!";
        else if (manufacturingYear == null) errorMessage = "Manufactury Year should be a number and greater than Zero!";
        else if (year == null) errorMessage = "Expiry year should be a number and greater than Zero!";
        else if (month == null) errorMessage = "Expiry month should be a number and greater than Zero!";
        else if (day == null) errorMessage = "Expiry day should be a number and greater than Zero!";
        else if (comprehensiveRadioButton.isSelected() && driverAge == null) errorMessage = "Driver Age should be a number and greater than Zero!";
        else if (comprehensiveRadioButton.isSelected() && level == null) errorMessage = "Level should be a number and greater than Zero!";

        //      Creation
        if (errorMessage.isEmpty()) {
            try {
                Car car = new Car(carModel, carType, manufacturingYear, price);
                MyDate expiryDate = MyDate.createValidDate(year, month, day);
                policy.setPolicyHolderName(holderName);
                policy.setNumberOfClaims(numberOfClaims);
                policy.setExpiryDate(expiryDate);
                policy.setCar(car);
                if (comprehensiveRadioButton.isSelected()) {
                    ((ComprehensivePolicy) policy).setDriverAge(driverAge);
                    ((ComprehensivePolicy) policy).setLevel(level);
                } else {
                    ((ThirdPartyPolicy) policy).setComments(comments);
                }
                JOptionPane.showMessageDialog(rootPane, "Policy '" + holderName + "' with ID (" + policyId + ")" + " updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                navigateBack();
                return;
            } catch (PolicyException e) {
                JOptionPane.showMessageDialog(rootPane, e, "Policy ID Out of Range!", JOptionPane.WARNING_MESSAGE);
                return;
            } catch (PolicyHolderNameException e) {
                errorMessage = e.toString();
            } catch (Exception e) {
                errorMessage = "Expiry Date Error: " + e.getMessage();
            }
        }
        JOptionPane.showMessageDialog(rootPane, errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_addPollicyButtonActionPerformed

    private void cancelPollicyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPollicyButtonActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Are you sure?", "Cancel Update", JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {
           navigateBack();
       }
    }//GEN-LAST:event_cancelPollicyButtonActionPerformed

    private void navigateBack() {
        dispose();
        userUI.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPollicyButton;
    private javax.swing.JButton cancelPollicyButton;
    private javax.swing.JTextField carModelField;
    private javax.swing.JComboBox<String> carTypeComboBox;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JRadioButton comprehensiveRadioButton;
    private javax.swing.JTextField dayField;
    private javax.swing.JTextField driverAgeField;
    private javax.swing.JLabel driverAgeLabel;
    private javax.swing.JTextField holderNameField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField levelField;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField manufacturingYearField;
    private javax.swing.JTextField monthField;
    private javax.swing.JTextField numberOfClaimsField;
    private javax.swing.JTextField policyIdField;
    private javax.swing.ButtonGroup policyTypeButtonGroup;
    private javax.swing.JTextField priceField;
    private javax.swing.JRadioButton thirdPartyRadioButton;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
